### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Dieterbe** [spenczar/fpc#1]
Hello Spencer,
this looks like an interesting algorithm. We're heavy users of the gorilla float compression algorithm (via the https://github.com/dgryski/go-tsz package) and I wondered how fpc compares.

To that end, I patched the eval program in the go-tsz library (i wrote this a while ago to get insights in compression performance across various types of input and lengths of the sequence being compressed)
like so:
```
diff --git a/eval/main.go b/eval/main.go
index f4ef015..1743fad 100644
--- a/eval/main.go
+++ b/eval/main.go
@@ -1,13 +1,16 @@
 package main
 
 import (
+       "bytes"
        "fmt"
-       "github.com/dgryski/go-tsz"
-       "github.com/dgryski/go-tsz/testdata"
+       //      "github.com/dgryski/go-tsz"
        "math"
        "math/rand"
        "os"
        "text/tabwriter"
+
+       "github.com/dgryski/go-tsz/testdata"
+       "github.com/spenczar/fpc"
 )
 
 // collection of 24h worth of minutely points, with different characteristics.
@@ -148,11 +151,16 @@ func main() {
        do := func(data []testdata.Point, comment string) string {
                str := ""
                for _, points := range intervals {
-                       s := tsz.New(data[0].T)
+                       buf := &bytes.Buffer{}
+                       w, err := fpc.NewWriterLevel(buf, 255)
+                       if err != nil {
+                               panic(err)
+                       }
                        for _, tt := range data[0:points] {
-                               s.Push(tt.T, tt.V)
+                               w.WriteFloat(tt.V)
                        }
-                       size := len(s.Bytes())
+                       w.Flush()
+                       size := buf.Len()
                        BPerPoint := float64(size) / float64(points)
                        str += fmt.Sprintf("\033[31m%d\033[39m\t%.2f\t", size, BPerPoint)
                }
```

and got the following panic:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/spenczar/fpc.(*fcm).predict(0xc4200143f0, 0x0)
	/home/dieter/go/src/github.com/spenczar/fpc/predictor.go:34 +0x38
github.com/spenczar/fpc.(*encoder).computeDiff(0xc420012300, 0x0, 0x1, 0xc42000e410)
	/home/dieter/go/src/github.com/spenczar/fpc/encode.go:198 +0x38
github.com/spenczar/fpc.(*encoder).encode(0xc420012300, 0x0, 0x0, 0xc42000e410, 0x1, 0x1, 0xc420041500)
	/home/dieter/go/src/github.com/spenczar/fpc/encode.go:218 +0x39
github.com/spenczar/fpc.(*blockEncoder).encode(0xc420052150, 0x0, 0x0, 0x0)
	/home/dieter/go/src/github.com/spenczar/fpc/encode.go:96 +0x6d
github.com/spenczar/fpc.(*Writer).writeUint64(0xc420014450, 0x0, 0x0, 0x0)
	/home/dieter/go/src/github.com/spenczar/fpc/writer.go:117 +0x5a
github.com/spenczar/fpc.(*Writer).writeFloat64(0xc420014450, 0x0, 0x0, 0x0)
	/home/dieter/go/src/github.com/spenczar/fpc/writer.go:110 +0x41
github.com/spenczar/fpc.(*Writer).WriteFloat(0xc420014450, 0x0, 0x0, 0x0)
	/home/dieter/go/src/github.com/spenczar/fpc/writer.go:70 +0x37
main.main.func1(0xc42008e000, 0x5a0, 0x5a0, 0x0, 0x0, 0xb9, 0x0)
	/home/dieter/go/src/github.com/dgryski/go-tsz/eval/main.go:160 +0x10e
main.main()
	/home/dieter/go/src/github.com/dgryski/go-tsz/eval/main.go:197 +0x187f
```

**Comment by Dieterbe** [comment]
I can also reproduce the panic with various other high compression levels. but for low compression levels like 10 or 16 it seems to work fine

**Comment by spenczar** [comment]
Thanks for the bug report. I'm able to reproduce these problems for very high compression levels. They appear in Martin Burscher's reference implementation from http://cs.txstate.edu/~mb92/research/FPC/, too.

Quite a few compression levels are actually forbidden in the reference implementation. A quick bash script running the reference code as `~/bin/fpc`:

```bash
for i in $(seq 1 255)
do
        ~/fpc $i < 10k.dat > /dev/null 2>/dev/null
        if [ $? -ne 0 ]
        then
                hex=$(echo "obase=16; $i" | bc)
                bin=$(echo "obase=2; $i" | bc)
                echo "failed  dec=$i  hex=$hex  bin=$bin"
        fi
done
```

The output shows blocks of numbers that are forbidden. In decimal, they are 43-63, 107-127, 171-191, 235-255.

This is tricky stuff. Clearly, we should return an error if you call NewWriterLevel with one of these poisonous compression levels, but I hope we can find some nicer way to warn users in documentation about these forbidden compression levels.

I'll make a revision to return an error for now.

**Comment by spenczar** [comment]
It gets worse. My Go implementation fails for any compression level of 35 or higher. 

It's extremely unlikely that someone should be using a compression ratio of more than 30. We need to allocate 16 * 2^(compression) bytes for the encoder. Maybe we should put a lower compression limit (32?) just to be safe, and more clearly warn that huge compression values don't help?

I'm concerned by the mismatch with the reference implementation, but so it goes.

**Comment by spenczar** [comment]
More explanation: the reference implementation was bugging out on 43-63, 107-127, 171-191 and 235-255 because my OS refused to allocate so much memory. But at 64, of course, the integer overflowed.

I think treating 32 as a max compression value is correct here.

**Comment by spenczar** [comment]
By the way, @Dieterbe, I've emailed with Martin Burtscher a bit about this algorithm. He recommended I take a look at SPDP (http://cs.txstate.edu/~burtscher/research/SPDP/), which doesn't yet have a paper describing it - just code. He says it has significant improvements, though. I haven't gotten around to implementing it, but I might if it sounds useful to you.

**Comment by Dieterbe** [comment]
> It's extremely unlikely that someone should be using a compression ratio of more than 30. We need to allocate 16 * 2^(compression) bytes for the encoder. Maybe we should put a lower compression limit (32?) just to be safe, and more clearly warn that huge compression values don't help?
> I'm concerned by the mismatch with the reference implementation, but so it goes.

I think this is fair.  I get OOM around the level 30 mark on my 32GB RAM laptop.
a theoretical level limit of 32=64GB is more than ok with me. Besides, I notice once you use higher levels, it takes more time to obtain results that aren't necessarily better (i see improvements and worsenings depending on the category of input data), so i would probably stick with the default of 10.
Is there a use case for machines with lots of ram (512GB, 1TB ?) that might want a level 33/34/35 ? (not that I would want this, just curious)

For now, go-tsz works well for us (uses the compression described in http://www.vldb.org/pvldb/vol8/p1816-teller.pdf) and seeking improvements in our float compression is currently low priority, I'ld like to study this implementation (and read the paper) in more detail at some point when I have spare time or something :)
